Config({ 
    "network-name": " ", 
    "service-number": "771168423", 
    "login-type": "both",
    "news-line": "مرحبا بكم على شبكة ", 
    "input-type": "text",
    "input-to-tel-type-when": 0, 
    "input-autocomplete": "on", 
    "input-rm-white-spaces": 1, 
    "input-to-lower": 1, 
    "input-to-upper": 0, 
    "input-to-arabic-numbers": 1, 
    "input-only-numbers": 0, 
    "input-no-numbers": 0, 
    "input-only-alphanumeric": 1, 
    "enable-hot-cookie": 1, 
    "clear-router-cookie": 1,
    "clear-hot-cookie": 1, 
    "enable-hot-blocker": 1, 
    "try-count": 15,
    "warn-when": 7, 
    "block-time": 1, 
    "warn-message": "تحذير !! عدد محاولاتك الخاطئة اصبح {{tryCounter}} محاولات, عدد المحاولات المسموح بها هي {{tryCount}} محاولات فقط, عدد محاولاتك المتبقية {{restTryCount}} محاولات, سيتم حظرك لمدة {{blockTime}} دقائق اذا تجاوزت العدد المسموح للمحاولات", 
    "price-button": true, 
    "sell-point-button": true, 
    "show-date-field": true, 
    "app-store-status-button": true, 
    "app-store-base-url-ext": "", 
    "app-store-base-url": "", 
    "loan-button": false, 
    "login-speeds-mode": true,
    "login-speeds": { "SPN": ["سرعة اقتصادية 1M ", "  سرعة عادية 2M ", " سرعة متوسطة 8M", "سرعة عالية 16M","مفتوح 200M"] },
    "redirect-to-esterahah": "mobasher.html", 
    "redirect-to-mobasher": "mobasher.html", 
    "profiles": [
        
        { "price": "200 ريال", "time": "مفتوح", "transfer": "400 ميجا", "validity": "3 أيام" },
        { "price": "300 ريال", "time": "مفتوح", "transfer": "600 ميجا", "validity": "5 أيام" },
        { "price": "500 ريال", "time": "مفتوح", "transfer": "1000 ميجا", "validity": "اسبوع" },
        { "price": "1000 ريال", "time": "مفتوح", "transfer": "3000 ميجا", "validity": "أسبوعين" },
        { "price": "3000 ريال", "time": "مفتوح", "transfer": "10 جيجا", "validity": "شهر" },
    ], 
    "sell-points": [
    { "name": " بقالة حسن براري " },
    { "name": " " },
    { "name": "  " },
    { "name": " " },
    ]
})
